__title__ = 'nest-client'
__description__ = 'Nest Web Client'
__url__ = 'https://github.com/dskrypa/nest-client'
__version__ = '2025.07.02-1'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2025 Doug Skrypa'
